services:
  - type: web
    name: task-planner-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false

  - type: static
    name: task-planner-client
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
